version: '3.8'

services:
  ptcg-standings:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ptcg-standings
    ports:
      - '5001:5001'
    volumes:
      - ./data:/app/data # Mount local data folder to the container
    environment:
      - TZ=Pacific/Auckland
    restart: unless-stopped
