name: Demo Deploy
on:
  workflow_run:
    workflows: ['Test Workflow']
    types:
      - completed

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "Deploying app"
